[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.pdo", "php82Extensions.tokenizer", "composer"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"