{{-- FILE PATH: resources/views/instructor/tests/export-pdf.blade.php --}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $test->title }} — Question Paper</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 30px; color: #111; }
        h1 { text-align:center; font-size:1.4rem; border-bottom:2px solid #1e40af; padding-bottom:8px; }
        .meta { text-align:center; font-size:.85rem; color:#555; margin-bottom:24px; }
        .section-title { background:#1e40af; color:#fff; padding:6px 12px; border-radius:4px; font-size:.9rem; margin-top:20px; margin-bottom:12px; }
        .question { margin-bottom:18px; }
        .q-num { font-weight:700; color:#1e40af; }
        .q-text { margin:4px 0 8px; font-size:.95rem; }
        .options { display:grid; grid-template-columns:1fr 1fr; gap:4px; }
        .option { font-size:.88rem; padding:3px 0; }
        .footer { text-align:center; font-size:.75rem; color:#999; margin-top:40px; border-top:1px solid #ddd; padding-top:10px; }
        @media print { .no-print { display:none; } }
    </style>
</head>
<body>
<div class="no-print" style="padding:12px;background:#f0f9ff;border:1px solid #bae6fd;border-radius:8px;margin-bottom:20px;font-size:.85rem">
    <strong>📄 Print this page</strong> using Ctrl+P (or Cmd+P on Mac) to save as PDF.
    &nbsp;<button onclick="window.print()" style="padding:4px 14px;background:#1e40af;color:#fff;border:none;border-radius:4px;cursor:pointer">🖨️ Print / Save PDF</button>
</div>

<h1>{{ $test->title }}</h1>
<div class="meta">
    Code: <strong>{{ $test->test_code }}</strong> &nbsp;|&nbsp;
    Duration: <strong>{{ $test->duration_minutes }} minutes</strong> &nbsp;|&nbsp;
    Total Marks: <strong>{{ $test->total_marks }}</strong>
    @if($test->negative_marking)
    &nbsp;|&nbsp; Negative Marking: <strong>-{{ $test->negative_marks }}</strong>
    @endif
</div>

@if($test->instructions)
<div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:6px;padding:10px 14px;margin-bottom:20px;font-size:.88rem">
    <strong>Instructions:</strong> {!! nl2br(e($test->instructions)) !!}
</div>
@endif

@php $qNum = 1; @endphp
@foreach($test->sections as $section)
<div class="section-title">{{ $section->title }}</div>
@foreach($section->questions->where('is_active', true) as $q)
<div class="question">
    <span class="q-num">Q{{ $qNum++ }}.</span>
    <span class="q-text">{{ $q->statement }}</span>
    <div class="options">
        @foreach(['a'=>'A','b'=>'B','c'=>'C','d'=>'D'] as $key=>$label)
        <div class="option">({{ $label }}) {{ $q->{'option_'.$key} }}</div>
        @endforeach
        @if($q->option_e)
        <div class="option">(E) {{ $q->option_e }}</div>
        @endif
    </div>
    <div style="font-size:.75rem;color:#999;margin-top:4px;">Marks: {{ $q->marks }}</div>
</div>
@endforeach
@endforeach

<div class="footer">
    Generated by SWF Portal &mdash; Student Welfare Foundation &mdash; swfhelpers@gmail.com
</div>
</body>
</html>